import{a as q,S as E,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="50519901-1dec8c4abba0943f2b3355c3a",R="https://pixabay.com/api/",B=15;async function f(t,s=1){const o={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:B};return(await q.get(R,{params:o})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const s=t.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:l,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${o}" alt="${e}" class="gallery-img" />
      </a>
      <div class="ul-info">
        <p class="ul-info-li">Likes:<span class="ul-info-li-p"> ${r}</span></p>
        <p class="ul-info-li">Views:<span class="ul-info-li-p"> ${l}</span></p>
        <p class="ul-info-li">Comments:<span class="ul-info-li-p"> ${w}</span></p>
        <p class="ul-info-li">Downloads:<span class="ul-info-li-p"> ${S}</span></p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",s),$.refresh()}function M(){m.innerHTML=""}function L(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function b(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const v=document.querySelector(".form"),p=v.querySelector("input"),O=document.querySelector(".load-more");document.querySelector(".gallery");d();c();let i=1,u="";v.addEventListener("submit",async t=>{t.preventDefault();const s=p.value.trim();if(!s){a.warning({message:"Please enter a search term!",position:"topRight"});return}u=s,i=1,M(),c(),L();try{const o=await f(u,i);if(!o.hits||o.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits),o.totalHits>i*15&&b()}catch(o){a.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}finally{d(),p.value=""}});O.addEventListener("click",async()=>{i+=1,L(),c();try{const t=await f(u,i);if(!t.hits||t.hits.length===0){a.info({message:"No more images available.",position:"topRight"}),c();return}y(t.hits);const s=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),i*15>=t.totalHits?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(t){a.error({message:"Failed to load more images. Please try again.",position:"topRight"}),console.error(t)}finally{d()}});
//# sourceMappingURL=index.js.map
